name: Deploy SIAF Automático

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Actualizar Código y Build en VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Definir la ruta de Node y NPM manualmente para esta sesión
            export PATH=$PATH:/root/.nvm/versions/node/v24.11.1/bin
            
            cd /var/www/SIAF
            git pull origin main
            
            # Backend
            cd server
            npm install --production
            
            # Frontend
            cd ../client
            npm install
            npm run build
            
            # Reiniciar con PM2 usando el nombre de tu proceso
            pm2 restart siaf-backend || pm2 start src/index.js --name siaf-backend