name: Deploy SIAF Automático

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Actualizar Código y Build en VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Cargar rutas de node y npm automáticamente
            source ~/.profile || source ~/.bashrc
            
            cd /var/www/SIAF
            git pull origin main
            
            # Backend
            cd server
            npm install --production
            
            # Frontend
            cd ../client
            npm install
            npm run build
            
            # Reiniciar con PM2 (Ajustado a tu nombre de proceso)
            pm2 restart siaf-backend || pm2 start src/index.js --name siaf-backend